### ISSUE TITLE
Not able to genarate deposit adress 

### ISSUE THREAD

**Issue by anujnetwork** [sparkswap/broker#285]
ubuntu@ip-10-0-1-122:~/sparkswap$ sparkswap wallet new-deposit-address BTC
{ Error: 13 INTERNAL: [WalletService:newDepositAddress] Call terminated before completion
    at Object.exports.createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.3/lib/node_modules/broker-cli/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/home/ubuntu/.nvm/versions/node/v8.11.3/lib/node_modules/broker-cli/node_modules/grpc/src/client_interceptors.js:1214:28)
    at InterceptingListener._callNext (/home/ubuntu/.nvm/versions/node/v8.11.3/lib/node_modules/broker-cli/node_modules/grpc/src/client_interceptors.js:590:42)
    at InterceptingListener.onReceiveStatus (/home/ubuntu/.nvm/versions/node/v8.11.3/lib/node_modules/broker-cli/node_modules/grpc/src/client_interceptors.js:640:8)
    at callback (/home/ubuntu/.nvm/versions/node/v8.11.3/lib/node_modules/broker-cli/node_modules/grpc/src/client_interceptors.js:867:24)
  code: 13,
  metadata: Metadata { _internal_repr: { timestamp: [Array] } },
  details: '[WalletService:newDepositAddress] Call terminated before completion' }

**Comment by treygriffith** [comment]
We've added some additional feedback to the CLI for cases when the broker is not up yet, and in an upcoming release we'll add more feedback specifically for when the blockchain backend is not yet synced.

If you're running into this issue again, let me know.
